name: M1 AUDUSD

on:
  workflow_dispatch:

jobs:
  AUDUSD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "2.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U git+git://github.com/Lu-Yi-Hsun/iqoptionapi.git
          pip install python-dateutil

      - name: Run Script
        run: python index.py PRACTICE AUDUSD
        env:
          IQU: ${{ secrets.IQU }}
          IQP: ${{ secrets.IQP }}

      - uses: actions/upload-artifact@v2
        with:
          name: AUDUSD
          path: logs/
