name: M1

on:
  workflow_dispatch:
    inputs:
      banca:
        description: "REAL | PRACTICE"
        required: true
        default: "PRACTICE"
      current:
        description: "USDJPY | EURJPY | USDCAD | EURUSD"
        required: true
        default: "USDJPY"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "2.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dateutil
          pip install -U git+git://github.com/Lu-Yi-Hsun/iqoptionapi.git

      - name: Run Script
        run: "python run.py ${{ github.event.inputs.banca }} ${{ github.event.inputs.current }}"

      - uses: actions/upload-artifact@v2
        with:
          name: logs
          path: logs/
